spring:
  datasource: # 数据库
    url: jdbc:mysql://47.93.60.69:3306/beannote
    username: root
    password: A_000000
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.beannote.beannote


